apiVersion: v1
kind: Service
metadata:
  name: qatar22-service
spec:
  type: NodePort
  selector:
    app: qatar22
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
